select setval('adsq_id_admin', (select max(id_admin) + 1 from adtb_admin) );
select setval('adsq_id_priv', (select max(id_priv) + 1 from adtb_privilegio) );
select setval('bktb_backup_id_backup_seq', (select max(id_backup) + 1 from bktb_backup) );
select setval('casq_id_bloco', (select max(id_bloco) + 1 from catb_condominio_bloco) );
select setval('casq_id_condominio', (select max(id_condominio) + 1 from catb_condominio) );
select setval('cbsq_id_carne', (select max(id_carne) + 1 from cbtb_carne) );
select setval('cbsq_id_cliente_produto', (select max(id_cliente_produto) + 1 from cbtb_cliente_produto) );
select setval('cbsq_id_comissao', (select max(id_comissao) + 1 from cbtb_comissao) );
select setval('cbsq_id_endereco_cobranca', (select max(id_endereco_cobranca) + 1 from cbtb_endereco_cobranca) );
select setval('cbsq_id_remessa', (select max(id_remessa) + 1 from cbtb_lote_cobranca) );
select setval('cbtb_faturas_id_cobranca_seq', (select max(id_cobranca) + 1 from cbtb_faturas) );
select setval('cfsq_id_cobranca', (select max(id_cobranca) + 1 from cftb_forma_pagamento) );
select setval('cfsq_id_nas', (select max(id_nas) + 1 from cftb_nas) );
select setval('cfsq_id_pop', (select max(id_pop) + 1 from cftb_pop) );
select setval('cfsq_id_rede', (select max(id_rede) + 1 from cftb_rede) );
select setval('cfsq_servidor_id_servidor', (select max(id_servidor) + 1 from cftb_servidor) );
select setval('cftb_links_id_link_seq', (select max(id_link) + 1 from cftb_links) );
select setval('clsq_id_cliente', (select max(id_cliente) + 1 from cltb_cliente) );
select setval('cnsq_id_conta', (select max(id_conta) + 1 from cntb_conta) );
select setval('cnsq_id_endereco_instalacao', (select max(id_endereco_instalacao) + 1 from cntb_endereco_instalacao) );
select setval('cxsq_id_fluxo', (select max(id_fluxo) + 1 from cxtb_fluxo) );
select setval('evsq_id_evento', (select max(id_evento) + 1 from evtb_evento) );
select setval('hdsq_id_grupo', (select max(id_grupo) + 1 from hdtb_grupo) );
select setval('lgsq_id_processo', (select max(id_processo) + 1 from lgtb_bloqueio_automatizado) );
select setval('lgtb_reagendamento_id_reagendamento_seq', (select max(id_reagendamento) + 1 from lgtb_reagendamento) );
select setval('pfsq_id_forma_pagamento', (select max(id_forma_pagamento) + 1 from pftb_forma_pagamento) );
select setval('pfsq_id_modelo_contrato', (select max(id_modelo_contrato) + 1 from pftb_modelo_contrato) );
select setval('prsq_id_produto', (select max(id_produto) + 1 from prtb_produto) );
select setval('spsq_id_spool', (select max(id_spool) + 1 from sptb_spool) );

-- select setval('blsq_carne_nossonumero', (select max() + 1 from ) );
-- select setval('blsq_nosso_numero_banco', (select max() + 1 from ) );
-- select setval('cbsq_id_cobranca', (select max() + 1 from ) );
-- select setval('cbtb_lote_cobranca_id_remessa_seq', (select max() + 1 from ) );
-- select setval('clsq_id_cliente_produto', (select max() + 1 from ) );
-- select setval('clsq_id_conta', (select max() + 1 from ) );
-- select setval('cxsq_autenticacao', (select max() + 1 from ) );
-- select setval('id_venda_seq', (select max() + 1 from ) );
-- select setval('lgsq_id_exclusao', (select max() + 1 from ) );
-- select setval('lgsq_id_remessa', (select max() + 1 from ) );
-- select setval('lgtb_backup_id_backup', (select max() + 1 from ) );
-- select setval('lgtb_contas_excluidas_id_excluida_seq', (select max() + 1 from ) );
-- select setval('lgtb_renovacao_id_renovacao_seq', (select max() + 1 from ) );
-- select setval('lgtb_restore_id_restore_seq', (select max() + 1 from ) );
-- select setval('lgtb_retorno_id_arquivo_seq', (select max() + 1 from ) );
-- select setval('lgtb_status_conta_id_processo_seq', (select max() + 1 from ) );
-- select setval('rdsq_id_accounting', (select max() + 1 from ) );
-- select setval('rdtb_accounting_session_id', (select max() + 1 from ) );
-- select setval('rdtb_log_id_log', (select max() + 1 from ) );
-- select setval('sptb_spool_id_spool', (select max() + 1 from ) );
-- select setval('sptb_spool_id_spool_seq', (select max() + 1 from ) );
-- select setval('', (select max() + 1 from ) );
